disabled_rules:
  - trailing_whitespace
  - force_cast

opt_in_rules:
  - empty_count

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length: 2

included:
  - Lunch-Machine

excluded:
  - Pods
  - DerivedData

